name: EliteMobs
version: 9.1.0-SNAPSHOT
author: MagmaGuy
main: com.magmaguy.elitemobs.EliteMobs
api-version: 1.14
softdepend:
- Multiverse-Core
- WorldGuard
- Vault
- PlaceholderAPI
- HolographicDisplays
- DiscordSRV
- LibsDisguises
- ModelEngine
- Geyser-Spigot
- MythicMobs
- LevelledMobs
- InfernalMobs
- FreeMinecraftModels

commands:
  elitemobs:
    description: Main command
    aliases:
      - em
  adventurersguild:
    description: Main command
    aliases:
      - ag

permissions:
  elitemobs.*:
    description: Gives access to all elitemobs commands
    children:
      elitemobs.stats: true
      elitemobs.checktier.others: true
      elitemobs.versionnotification: true
      elitemobs.currency.check.others: true
    default: op
  elitemobs.stats:
    description: Allows players to run /elitemobs stats
    default: op
  elitemobs.version:
    description: Allows players to run /elitemobs version
    default: true
  elitemobs.shop.npc:
    description: Allows players to interact with NPCs for dynamic shops
    default: true
  elitemobs.shop.command:
    description: Allows players to open the dynamic shop menu through commands
    default: true
  elitemobs.customshop.npc:
    description: Allows players to interact with NPCs for dynamic shops
    default: true
  elitemobs.customshop.command:
    description: Allows players to open the dynamic shop menu through commands
    default: true
  elitemobs.currency.pay:
    description: Allows players to run /elitemobs pay [username] [amount]
    default: true
  elitemobs.currency.check:
    description: Allows players to run /elitemobs wallet
    default: true
  elitemobs.currency.check.others:
    description: Allows players to run /elitemobs check [username]
    default: op
  elitemobs.events:
    description: Allows players to launch all events
    default: true
  elitemobs.checktier.others:
    description: Allows players to run /elitemobs checktier [player]
    default: op
  elitemobs.gettier:
    description: Allows players to run /elitemobs gettier [tier]
    default: op
  elitemobs.versionnotification:
    description: Allows players to get notified about plugin updates
    default: op
  elitemobs.adventurersguild.teleport:
    description: Allows players to teleport to the adventurer's guild hub using /ag
    default: true
  elitemobs.adventurersguild.command:
    description: Allows players to rank menu using the /em adventurersguild command
    default: true
  elitemobs.rank.command:
    description: Allows players to open the rank menu through /em rank
    default: true
  elitemobs.rank.npc:
    description: Allows players to access the /em rank menu through NPCs
    default: true
  elitemobs.quest.command:
    description: Allows players to take on quests via command
    default: true
  elitemobs.quest.npc:
    description: Allows players to take on quests via EliteMobs NPC
    default: true
  elitemobs.dungeontp:
    description: Allows players to teleport to an elitemobs-set location
    default: true
  elitemobs.spawntp:
    description: Allows players to teleport to the default spawn location of the server.
    default: true
  elitemobs.back.npc:
    description: Allows players to interact with an npc to go back to a previous location.
    default: true
  elitemobs.shareitem:
    description: Shares a held Elite Item on chat.
    default: true
  elitemobs.scrap.npc:
    description: Allows players to scrap items at an npc
    default: true
  elitemobs.scrap.command:
    description: Allows players to scrap items using a command
    default: true
  elitemobs.smelt.command:
    description: Allows players to smelt items using a command
    default: true
  elitemobs.smelt.npc:
    description: Allows players to smelt items using an npc
    default: true
  elitemobs.repair.command:
    description: Allows players to use the repair command to open the menu for repairing elite items
    default: true
  elitemobs.repair.npc:
    description: Allows players to interact with the NPC for repairing items
    default: true
  elitemobs.refiner.command:
    description: Allows players to use the refiner command to open the menu for upgrading Elite Scrap
    default: true
  elitemobs.refiner.npc:
    description: Allows players to interact with the NPC for upgrading Elite Scrap
    default: true
  elitemobs.enhancer.command:
    description: Allows players to use the enhancer command to open the menu for upgrading Elite Items
    default: true
  elitemobs.enhancer.npc:
    description: Allows players to interact with the NPC for upgrading Elite Items
    default: true
  elitemobs.unbind.command:
    description: Allows players to use the unbind command to open the menu to unbind Elite Items
    default: true
  elitemobs.unbind.npc:
    description: Allows players to interact with the unbinder NPC to unbind Elite Items
    default: true
  elitemobs.soulbind.bypass:
    description: Allows users to bypass the soulbind restrictions. Only recommended for admins!
    default: false
  elitequest.*:
    description: Used for quest-related permissions
    default: not op
  elitemobs.enchant.npc:
    description: Allows players to interact with the enchanter NPC to enchant Elite Items
    default: true
  elitemobs.enchant.command:
    description: Allows players to use the enchant command to enchant Elite Items
    default: true
  elitemobs.arena.menu:
    description: Allows players to open the Arena menu and join an Arena.
    default: true
  elitemobs.debug:
    description: Allows players to have access to the player/bosses debug command.
    default: true
  elitemobs.discord.link:
    description: Allows players to have access to the Discord link command.
    default: true
  elitemobs.discord.message:
    description: Allows players to have access to the DiscordSRV message debug command.
    default: op
  elitemobs.event.start:
    description: Allows players to start specific events.
    default: op
  elitemobs.fireball:
    description: Allows players to shoot a fireball at the pointer's location.
    default: op
  elitemobs.help:
    description: Allows players to see all available EliteMobs commands.
    default: op
  elitemobs.kill.kill:
    description: Allows players to kill all elites.
    default: op
  elitemobs.kill.radius:
    description: Allows players to kill all elites in the specified radius.
    default: op
  elitemobs.kill.type:
    description: Allows players to kill all elites of the specified type.
    default: op
  elitemobs.kill.type.radius:
    description: Allows players to kill all elites of the specified type within the given radius.
    default: op
  elitemobs.language:
    description: Allows players to set the language that the server will use for EliteMobs.
    default: op
  elitemobs.loot.debug:
    description: Allows players to equip themselves with a complete armor set, weapons set of the specified level, and food for testing purposes.
    default: op
  elitemobs.loot.give:
    description: Allows players to give the specified loot to a specific player.
    default: op
  elitemobs.loot.menu:
    description: Allows players to open the loot menu and select any loot they want.
    default: op
  elitemobs.loot.random:
    description: Allows players to get random loot of the specified level.
    default: op
  elitemobs.loot.simulate:
    description: Allows players to get simulated loot drops for the specified level and player.
    default: op
  elitemobs.loot.simulate.times:
    description: Allows players to get simulated loot drops for a specified number of times for the given level and player.
    default: op
  elitemobs.loot.stats:
    description: Allows players to see EliteMobs stats for the currently held item.
    default: true
  elitemobs.loot.stats:
    description: Allows players to see EliteMobs stats for the currently held item.
    default: op
  elitemobs.money.add.all:
    description: Allows players to give every player on the server the specified amount of money.
    default: op
  elitemobs.money.add.player:
    description: Allows players to give the specified amount of money to the designated player.
    default: op
  elitemobs.money.check.self:
    description: Allows players to check their EliteMobs currency.
    default: true
  elitemobs.money.check.player:
    description: Allows players to check the currency of the specified player.
    default: op
  elitemobs.money.remove:
    description: Allows players to deduct the specified amount of currency from a player.
    default: op
  elitemobs.money.set:
    description: Allows players to set the specified amount of currency for the specified player.
    default: op
  elitemobs.package:
    description: Allows players to package an EliteMobs dungeon for distribution.
    default: op
  elitemobs.place.boss:
    description: Allows players to add a spawn location for the specified boss at their current location.
    default: op
  elitemobs.place.npc:
    description: Allows players to permanently add an NPC to the location the user is standing on.
    default: op
  elitemobs.place.treasure:
    description: Allows players to permanently add a treasure chest to the location the user is standing on.
    default: op
  elitemobs.place.wormhole:
    description: Allows players to permanently add a wormhole teleport at their current location.
    default: op
  elitemobs.quest.bypass:
    description: Allows players to bypass permission restrictions for elite quests.
    default: op
  elitemobs.quest.complete:
    description: Allows players to force complete all of their currently active elite quests. For debugging use only.
    default: op
  elitemobs.quest.leave:
    description: Allows players to leave a quest. Used via menu, can't be directly used.
    default: op
  elitemobs.quest.reset.all:
    description: Allows players to reset all quests for a specific player.
    default: op
  elitemobs.quest.reset.quest:
    description: Allows players to reset a specific quest for a specific player.
    default: op
  elitemobs.rank.set:
    description: Allows players to manually set a player's guild rank to a the prestige level and guild level specified.
    default: op
  elitemobs.reload:
    description: Allows players to reload EliteMobs.
    default: op
  elitemobs.remove:
    description: Allows players to toggle removal mode for EliteMobs, which can permanently remove any EliteMobs-related content.
    default: op
  elitemobs.respawn:
    description: Allows players to force respawn all regional bosses.
    default: op
  elitemobs.setup.main:
    description: Allows players to have access to the main command for setting up EliteMobs.
    default: op
  elitemobs.setup.done:
    description: Allows players to toggle whether the setup message will show up in the server chat.
    default: op
  elitemobs.setup.toggle:
    description: Allows players to toggle the installation of specified EliteMobs content.
    default: op
  elitemobs.shop.custom:
    description: Allows players to open the EliteMobs shop for custom items for the specified player.
    default: op
  elitemobs.shop.sell.player:
    description: Allows players to open the EliteMobs shop for custom items for the specified player.
    default: op
  elitemobs.spawn.boss.at:
    description: Allows players to spawn a custom boss at the specified location.
    default: op
  elitemobs.spawn.boss:
    description: Allows players to spawn a custom boss at the location the player is looking at.
    default: op
  elitemobs.spawn.boss.at.level:
    description: Allows players to spawn a custom boss at the specified location with the specified level.
    default: op
  elitemobs.spawn.boss.level:
    description: Allows players to spawn a custom boss at the location the user is looking at with the specified level.
    default: op
  elitemobs.spawn.elite:
    description: Allows players to spawn an elite of a specified type and level, optionally with specific powers, at the targeted location.
    default: op
  elitemobs.spawn.elite.at:
    description: Allows players to spawn an elite of the specified type and level, optionally with specified powers, at the chosen location.
    default: op
  elitemobs.transitiveblocks.cancel:
    description: Allows players to cancel transitive block registration.
    default: op
  elitemobs.transitiveblocks.edit.area:
    description: Allows players to edit large transitive blocks areas for use by regional bosses.
    default: op
  elitemobs.transitiveblocks.edit.edit:
    description: Allows players to edit transitive blocks for use by regional bosses.
    default: op
  elitemobs.transitiveblocks.register.area:
    description: Allows players to register large transitive blocks areas for use by regional bosses.
    default: op
  elitemobs.transitiveblocks.register.register:
    description: Allows players to register transitive blocks for use by regional bosses.
    default: op
  elitemobs.unbind.force:
    description: Allows players to forcefully unbind a held item.
    default: op
  elitemobs.version:
    description: Allows players to check the server's EliteMobs plugin version.
    default: op
