name: EliteMobs
version: 3.0.18
author: MagmaGuy
main: com.magmaguy.elitemobs.EliteMobs
softdepend: [Multiverse-Core]
commands:
  elitemobs:
    description: Catch-all command
    usage: /elitemobs
    aliases: [em]
permissions:
  elitemobs.*:
    description: Gives access to all elitemobs commands
    children:
      elitemobs.stats: true
      elitemobs.shop: true
      elitemobs.getloot: true
      elitemobs.simloot: true
      elitemobs.reload.configs: true
      elitemobs.reload.loot: true
      elitemobs.giveloot: true
      elitemobs.spawnmob: true
      elitemobs.killall.aggressiveelites: true
      elitemobs.killall.passiveelites: true
      elitemobs.currency.user: true
      elitemobs.currency.subtract: true
      elitemobs.currency.set: true
      elitemobs.currency.check: true
      elitemobs.currency.add: true
  elitemobs.currency.user:
    description: Gives access to the commands users need to use the economy features (shops, paying other players)
    children:
      elitemobs.shop: true
      elitemobs.customshop: true
      elitemobs.pay: true
      elitemobs.wallet: true
  elitemobs.killall.*:
      description: Allows players to run /elitemobs killall passiveelites and /elitemobs killall aggressiveelites
      children:
        elitemobs.killall.aggressiveelites: true
        elitemobs.killall.passiveelites: true
  elitemobs.stats:
    description: Allows players to run /elitemobs stats
    default: op
  elitemobs.getloot:
    description: Allow players to run /elitemobs getloot
    default: op
  elitemobs.simloot:
    description: Allow players to run /elitemobs simloot
    default: op
  elitemobs.reload.configs:
    decription: Allow players to run /elitemobs reload config
    default: op
  elitemobs.reload.loot:
    decription: Allow players to run /elitemobs reload loot
    default: op
  elitemobs.giveloot:
    description: Allow players to run /elitemobs giveloot [playername] random/[loot name]
    default: op
  elitemobs.spawnmob:
    description: Allow players to run /elitemobs SpawnMob [mobType] [mobLevel] [mobPower] [mobPower(just keep adding until done)]
    default: op
  elitemobs.scoreboard:
    description: Shows a scoreboard with info about the elite mob a player might be standing next to
    default: false
  elitemobs.killall.aggressiveelites:
    description: Allows players to run /elitemobs killall aggressiveelites
    default: op
  elitemobs.killall.passiveelites:
    description: Allows players to run /elitemobs killall passiveelites
    default: op
  elitemobs.shop:
    description: Allows players to run /elitemobs shop
    default: op
  elitemobs.customshop:
    decription: Allows players to run /elitemobs customshop
    default: op
  elitemobs.currency.pay:
    description: Allows players to run /elitemobs pay [username] [amount]
    default: op
  elitemobs.currency.add:
    description: Allows players to run /elitemobs add [username] [amount]
    default: op
  elitemobs.currency.subtract:
    description: Allows players to run /elitemobs subtract [username] [amount]
    default: op
  elitemobs.currency.set:
    description: Allows players to run /elitemobs set [username] [amount]
    default: op
  elitemobs.currency.check:
    decription: Allows players to run /elitemobs check [username]
    default: op
  elitemobs.currency.wallet:
    decription: Allows players to run /elitemobs wallet
    default: op
