name: EliteMobs
version: 1.4.0
author: MagmaGuy
main: com.magmaguy.elitemobs.EliteMobs
commands:
  elitemobs:
    description: Tells a player the statistics of the
    usage: /elitemobs
    aliases: [em]
permissions:
  elitemobs.*:
    description: Gives access to all elitemobs commands
    children:
      elitemobs.stats: true
      elitemobs.getloot: true
      elitemobs.reload.config: true
      elitemobs.reload.loot: true
      elitemobs.giveloot: true
      elitemobs.spawnmob: true
  elitemobs.stats:
    description: Allows players to run /elitemobs stats
    default: op
  elitemobs.getloot:
    description: Allow players to run /elitemobs getloot
    default: op
  elitemobs.reload.config:
    decription: Allow players to run /elitemobs reload config
    default: op
  elitemobs.reload.loot:
      decription: Allow players to run /elitemobs reload loot
      default: op
  elitemobs.giveloot:
    description: Allow players to run /elitemobs giveloot [playername] random/[loot name]
    default: op
  elitemobs.spawnmob:
    description: Allow players to run /elitemobs spawnmob [mobType] [mobLevel] [mobPower] [mobPower(just keep adding until done)]
    default: op
